#!/usr/bin/env bash
#
# Patient Flow OS — one-shot deploy to a fresh Ubuntu VPS.
#
# Does everything: installs Docker if missing, writes .env.production (from flags
# or interactive prompts), brings up the hardened prod stack behind Caddy/HTTPS,
# and waits until the backend reports healthy.
#
# Run from the backend/ directory (where the compose files live):
#
#   sudo ./deploy.sh --domain api.myclinic.com
#
# Non-interactive example (CI / re-runs):
#
#   sudo ./deploy.sh \
#     --domain api.myclinic.com \
#     --db-password "$(openssl rand -hex 24)" \
#     --redis-password "$(openssl rand -hex 24)" \
#     --jwt-secret "$(openssl rand -hex 32)" \
#     --msg91-key KEY --razorpay-key-id ID --razorpay-key-secret SECRET
#
# Secrets already present in an existing .env.production are preserved unless a
# flag overrides them, so re-running to update code is safe.
set -euo pipefail

cd "$(dirname "$0")"

COMPOSE="docker-compose.prod.yml"
ENV_FILE=".env.production"

# ── defaults / arg parsing ────────────────────────────────────────────────
DOMAIN=""; DB_PASSWORD=""; REDIS_PASSWORD=""; JWT_SECRET=""
MSG91_KEY=""; MSG91_SENDER=""; MSG91_TEMPLATE=""
RZP_KEY_ID=""; RZP_KEY_SECRET=""; RZP_WEBHOOK_SECRET=""
FCM_PATH=""; SEED_ON_START=""

for arg in "$@"; do
  case "$arg" in
    --domain=*)              DOMAIN="${arg#*=}" ;;
    --domain)                shift; DOMAIN="${1:-}" ;;
    --db-password=*)         DB_PASSWORD="${arg#*=}" ;;
    --redis-password=*)      REDIS_PASSWORD="${arg#*=}" ;;
    --jwt-secret=*)          JWT_SECRET="${arg#*=}" ;;
    --msg91-key=*)           MSG91_KEY="${arg#*=}" ;;
    --msg91-sender=*)        MSG91_SENDER="${arg#*=}" ;;
    --msg91-template=*)      MSG91_TEMPLATE="${arg#*=}" ;;
    --razorpay-key-id=*)     RZP_KEY_ID="${arg#*=}" ;;
    --razorpay-key-secret=*) RZP_KEY_SECRET="${arg#*=}" ;;
    --razorpay-webhook-secret=*) RZP_WEBHOOK_SECRET="${arg#*=}" ;;
    --fcm-path=*)            FCM_PATH="${arg#*=}" ;;
    --no-seed)               SEED_ON_START="false" ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  esac
done

log() { printf '\033[1;34m[deploy]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[deploy] ERROR:\033[0m %s\n' "$*" >&2; }

# Read existing value from .env.production (so re-runs keep prior secrets).
prev() { [ -f "$ENV_FILE" ] && sed -n "s/^$1=//p" "$ENV_FILE" | head -n1 || true; }

# ── 1. install Docker if missing ──────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log "Docker not found — installing via get.docker.com ..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
else
  log "Docker present: $(docker --version)"
fi
if ! docker compose version >/dev/null 2>&1; then
  err "'docker compose' (v2) plugin missing. Install docker-compose-plugin and re-run."
  exit 1
fi

# ── 2. resolve config (flags > existing .env > prompt/generate) ───────────
[ -z "$DOMAIN" ]         && DOMAIN="$(prev DOMAIN)"
if [ -z "$DOMAIN" ]; then
  read -rp "Domain (DNS A record must already point here, e.g. api.myclinic.com): " DOMAIN
fi
[ -z "$DOMAIN" ] && { err "DOMAIN is required (Caddy needs it for HTTPS)."; exit 1; }

[ -z "$DB_PASSWORD" ]    && DB_PASSWORD="$(prev POSTGRES_PASSWORD)"
[ -z "$DB_PASSWORD" ]    && { DB_PASSWORD="$(openssl rand -hex 24)"; log "Generated Postgres password."; }

[ -z "$REDIS_PASSWORD" ] && REDIS_PASSWORD="$(prev REDIS_PASSWORD)"
[ -z "$REDIS_PASSWORD" ] && { REDIS_PASSWORD="$(openssl rand -hex 24)"; log "Generated Redis password."; }

[ -z "$JWT_SECRET" ]     && JWT_SECRET="$(prev JWT_SECRET)"
[ -z "$JWT_SECRET" ]     && { JWT_SECRET="$(openssl rand -hex 32)"; log "Generated JWT secret."; }

# Optional integrations: flag > existing value > blank (dev-fallback stays on).
[ -z "$MSG91_KEY" ]          && MSG91_KEY="$(prev MSG91_AUTH_KEY)"
[ -z "$MSG91_SENDER" ]       && MSG91_SENDER="$(prev MSG91_SENDER_ID)"
[ -z "$MSG91_TEMPLATE" ]     && MSG91_TEMPLATE="$(prev MSG91_OTP_TEMPLATE_ID)"
[ -z "$RZP_KEY_ID" ]         && RZP_KEY_ID="$(prev RAZORPAY_KEY_ID)"
[ -z "$RZP_KEY_SECRET" ]     && RZP_KEY_SECRET="$(prev RAZORPAY_KEY_SECRET)"
[ -z "$RZP_WEBHOOK_SECRET" ] && RZP_WEBHOOK_SECRET="$(prev RAZORPAY_WEBHOOK_SECRET)"
[ -z "$FCM_PATH" ]           && FCM_PATH="$(prev FCM_SERVICE_ACCOUNT_PATH)"
[ -z "$SEED_ON_START" ]      && { SEED_ON_START="$(prev SEED_ON_START)"; [ -z "$SEED_ON_START" ] && SEED_ON_START="true"; }

# ── 3. write .env.production ───────────────────────────────────────────────
log "Writing $ENV_FILE ..."
umask 077   # secrets file readable only by owner
cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Contains secrets.
DOMAIN=$DOMAIN
POSTGRES_PASSWORD=$DB_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
JWT_SECRET=$JWT_SECRET
OTP_EXPIRY_SECONDS=300
SEED_ON_START=$SEED_ON_START

MSG91_AUTH_KEY=$MSG91_KEY
MSG91_SENDER_ID=$MSG91_SENDER
MSG91_OTP_TEMPLATE_ID=$MSG91_TEMPLATE
INTEGRATIONS_TEST_MOBILE=

RAZORPAY_KEY_ID=$RZP_KEY_ID
RAZORPAY_KEY_SECRET=$RZP_KEY_SECRET
RAZORPAY_WEBHOOK_SECRET=$RZP_WEBHOOK_SECRET

FCM_SERVICE_ACCOUNT_PATH=$FCM_PATH
FCM_SERVICE_ACCOUNT_JSON=
NOTIFY_APPROACHING_AHEAD=3
NOTIFY_ARRIVAL_AHEAD=1
EOF

mkdir -p secrets   # so the read-only bind mount in compose always exists

# ── 4. build + start ───────────────────────────────────────────────────────
log "Building and starting the stack ..."
docker compose -f "$COMPOSE" --env-file "$ENV_FILE" up -d --build

# ── 5. wait for backend health ─────────────────────────────────────────────
log "Waiting for backend to become healthy (migrations + seed run first) ..."
for i in $(seq 1 40); do
  status="$(docker inspect --format '{{.State.Health.Status}}' pfos_backend 2>/dev/null || echo starting)"
  if [ "$status" = "healthy" ]; then
    log "Backend is healthy."
    docker compose -f "$COMPOSE" --env-file "$ENV_FILE" ps
    cat <<DONE

✅ Deployed. https://$DOMAIN (Caddy is issuing the TLS cert on first request —
   give it ~30s, then open the URL).

Next:
  - Logs:    docker compose -f $COMPOSE --env-file $ENV_FILE logs -f backend
  - Update:  git pull && ./deploy.sh --domain $DOMAIN   (re-uses saved secrets)
  - Backup:  ./backup.sh   (add to cron)
DONE
    exit 0
  fi
  printf '.'; sleep 5
done

err "Backend did not become healthy in time. Recent logs:"
docker compose -f "$COMPOSE" --env-file "$ENV_FILE" logs --tail=50 backend
exit 1
