services:
  postgres:
    image: postgres:16-alpine
    container_name: pfos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pfos
      POSTGRES_PASSWORD: pfos_local_pw
      POSTGRES_DB: patient_flow_os
    ports:
      - "5432:5432"
    volumes:
      - pfos_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pfos -d patient_flow_os"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: pfos_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - pfos_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pfos_pgdata:
  pfos_redisdata:
